// <auto-generated />
using System;
using Infraestructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Buy", b =>
                {
                    b.Property<int>("OrderbuyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderbuyId"));

                    b.Property<DateTime>("DateEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateStar")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderbuyId");

                    b.ToTable("buys");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "CUBS"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "SCOOTERS"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "CALLE"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "ENDURO"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "TOURING"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "NAKED"
                        },
                        new
                        {
                            CategoryId = 7,
                            Name = "RETRO"
                        },
                        new
                        {
                            CategoryId = 8,
                            Name = "DEPORTIVAS"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Client", b =>
                {
                    b.Property<Guid>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            ClientId = new Guid("9815e175-2967-4200-93e1-6088ba9387d9"),
                            Addres = "MZA30",
                            Dni = 41539440,
                            Email = "Giuliano@gmail.com",
                            Locality = "CLAYPOLE",
                            Name = "Giuliano",
                            Phone = 1141462757,
                            Province = "BS AS",
                            Surname = "Mendoza"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Dealer", b =>
                {
                    b.Property<Guid>("dealerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Cuit")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameProv")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ReasonSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("dealerID");

                    b.ToTable("Dealers");
                });

            modelBuilder.Entity("Domain.Entities.Moto", b =>
                {
                    b.Property<Guid>("MotoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Age")
                        .HasColumnType("datetime2");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ChasisNum")
                        .HasColumnType("int");

                    b.Property<int>("Cylinder")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<int>("EngineNum")
                        .HasColumnType("int");

                    b.Property<string>("Mark")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("MotoName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("StockCurrent")
                        .HasColumnType("int");

                    b.Property<int>("StockMax")
                        .HasColumnType("int");

                    b.Property<int>("StockMin")
                        .HasColumnType("int");

                    b.Property<string>("imageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MotoId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Moto");

                    b.HasData(
                        new
                        {
                            MotoId = new Guid("999e7caa-6220-44be-a806-d6ef739d5aee"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1034),
                            CategoryId = 1,
                            ChasisNum = 87654321,
                            Cylinder = 110,
                            Description = "La CORVEN-ENERGYFULL110 es una motocicleta que combina un diseño deportivo y elegante, ideal para la ciudad y recorridos de media distancia. Equipado con un motor de 110cc, 4 tiempo.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "CORVEN",
                            Model = "ENERGYFULL110",
                            MotoName = "CORVEN-ENERGYFULL110",
                            Price = 1599900m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053169650_a289468e65_c.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("3a9b02d0-a8ec-4bc3-a35a-a860c3d3ee12"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1049),
                            CategoryId = 1,
                            ChasisNum = 87654321,
                            Cylinder = 110,
                            Description = "La CORVEN-ENERGYTUNNING110 es una motocicleta que combina un diseño deportivo y elegante, ideal para la ciudad y recorridos de media distancia. Equipado con un motor de 110cc, 4 tiempo.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "CORVEN",
                            Model = "ENERGYTUNNING110",
                            MotoName = "CORVEN-ENERGYTUNNING110",
                            Price = 1900000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052965873_54860b1c3b_z.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("7df8bedc-9215-48c7-8f58-3fe9f1c50c62"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1052),
                            CategoryId = 1,
                            ChasisNum = 87654321,
                            Cylinder = 110,
                            Description = "La COVERN-ENERGYBASE110 es una motocicleta que combina un diseño deportivo y elegante, ideal para la ciudad y recorridos de media distancia. Equipado con un motor de 110cc, 4 tiempo.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "CORVEN",
                            Model = "ENERGYBASE110",
                            MotoName = "COVERN-ENERGYBASE110",
                            Price = 1450000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052723341_e5952e81c9_z.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("95390e07-8f60-41be-8a59-49f9586e9858"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1055),
                            CategoryId = 1,
                            ChasisNum = 87654321,
                            Cylinder = 110,
                            Description = "La COVERN-MIRAGEFULL110 es una motocicleta que combina un diseño deportivo y elegante, ideal para la ciudad y recorridos de media distancia. Equipado con un motor de 110cc, 4 tiempo.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "CORVEN",
                            Model = "MIRAGEFULL110",
                            MotoName = "COVERN-MIRAGEFULL110",
                            Price = 1090000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052723361_bee58fba5d_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("f1d00837-88d2-4c4e-b52e-db567ccb22a8"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1057),
                            CategoryId = 1,
                            ChasisNum = 87654321,
                            Cylinder = 110,
                            Description = "La GILERA-SMASHAUTOMATICA110 es una motocicleta que combina un diseño deportivo y elegante, ideal para la ciudad y recorridos de media distancia. Equipado con un motor de 110cc, 4 tiempo.",
                            Discount = 10,
                            EngineNum = 12345678,
                            Mark = "GILERA",
                            Model = "SMASHAUTOMATICA110",
                            MotoName = "GILERA-SMASHAUTOMATICA110",
                            Price = 1500000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052723316_28593e4b8e_c.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("b6f1d7ab-562d-4611-919c-3376fa404211"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1060),
                            CategoryId = 1,
                            ChasisNum = 87654321,
                            Cylinder = 110,
                            Description = "La GILERA-SMASHBASE110 es una motocicleta que combina un diseño deportivo y elegante, ideal para la ciudad y recorridos de media distancia. Equipado con un motor de 110cc, 4 tiempo.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "GILERA",
                            Model = "SMASHBASE110",
                            MotoName = "GILERA-SMASHBASE110",
                            Price = 1400000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052965823_4aa76e5ffe_z.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("b03a3901-1440-42e0-8b10-4ac345aebc70"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1095),
                            CategoryId = 1,
                            ChasisNum = 87654321,
                            Cylinder = 110,
                            Description = "La GILERA-SMASHFULL110 es una motocicleta que combina un diseño deportivo y elegante, ideal para la ciudad y recorridos de media distancia. Equipado con un motor de 110cc, 4 tiempo.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "GILERA",
                            Model = "SMASHFULL110",
                            MotoName = "GILERA-SMASHFULL110",
                            Price = 1700000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052723251_e0e1709bfc_c.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("2d6a3a58-0cac-4fe1-9888-57f18e50380d"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1097),
                            CategoryId = 1,
                            ChasisNum = 87654321,
                            Cylinder = 110,
                            Description = "La GILERA-SMASHX125 es una motocicleta que combina un diseño deportivo y elegante, ideal para la ciudad y recorridos de media distancia. Equipado con un motor de 110cc, 4 tiempo.",
                            Discount = 5,
                            EngineNum = 12345678,
                            Mark = "GILERA",
                            Model = "SMASHX125",
                            MotoName = "GILERA-SMASHX125",
                            Price = 2300000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052965798_d10760455e_c.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("6e80b2ff-282f-4750-9d19-df6731cd446a"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1102),
                            CategoryId = 2,
                            ChasisNum = 87654321,
                            Cylinder = 125,
                            Description = "La HONDA-NEWELITE cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 125cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "NEWELITE",
                            MotoName = "HONDA-NEWELITE",
                            Price = 6600000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052967503_31e3785e44_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("d311679b-b5c7-4a3d-973b-72f3eac71e5d"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1105),
                            CategoryId = 2,
                            ChasisNum = 87654321,
                            Cylinder = 150,
                            Description = "La HONDA-PCX150 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 150cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "PCX150",
                            MotoName = "HONDA-PCX150",
                            Price = 7990000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053049594_235673c725_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("c2ea9c88-ff8d-48ba-aecd-cbf9430528cb"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1107),
                            CategoryId = 2,
                            ChasisNum = 87654321,
                            Cylinder = 160,
                            Description = "La HONDA-PCX160 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 160cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "PCX160",
                            MotoName = "HONDA-PCX160",
                            Price = 7990000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053171235_4a4271923d_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("fcd88600-16a3-4d9e-8d37-d388c3a3c6a9"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1110),
                            CategoryId = 2,
                            ChasisNum = 87654321,
                            Cylinder = 125,
                            Description = "La YAMAHA-FASCINO125 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 125cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "FASCINO125",
                            MotoName = "YAMAHA-FASCINO125",
                            Price = 4000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053171220_d996053cef_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("e4a2d445-13f3-49a7-90ab-e140ccc64906"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1112),
                            CategoryId = 2,
                            ChasisNum = 87654321,
                            Cylinder = 125,
                            Description = "La YAMAHA-MADRID125 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 125cc, 4 tiempos.",
                            Discount = 10,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "MADRID125",
                            MotoName = "YAMAHA-MADRID125",
                            Price = 6600000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053049564_8a9b9bf027_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("2e79f178-c74e-4fef-92fc-209425a64386"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1115),
                            CategoryId = 2,
                            ChasisNum = 87654321,
                            Cylinder = 155,
                            Description = "La YAMAHA-NMAXCONNECTED155 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 155cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "NMAXCONNECTED155",
                            MotoName = "YAMAHA-NMAXCONNECTED155",
                            Price = 7600000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052967493_6727664557_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("20658076-8f40-4243-a58d-c957a9dc4215"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1117),
                            CategoryId = 2,
                            ChasisNum = 87654321,
                            Cylinder = 125,
                            Description = "La YAMAHA-RAYZR125 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 125cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "RAYZR125",
                            MotoName = "YAMAHA-RAYZR125",
                            Price = 4000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54051853037_ed7616af9b_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("cd40a09b-7756-4add-9719-5da35389fa0f"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1120),
                            CategoryId = 3,
                            ChasisNum = 87654321,
                            Cylinder = 250,
                            Description = "La ROUSER-N250 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 250cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "ROUSER",
                            Model = "N250",
                            MotoName = "ROUSER-N250",
                            Price = 6000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053047864_2d248790ed_z.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("f3a7dc48-ff3f-45e5-a28b-827a75771026"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1124),
                            CategoryId = 3,
                            ChasisNum = 87654321,
                            Cylinder = 160,
                            Description = "La ROUSER-NS125 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 160cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "ROUSER",
                            Model = "NS125",
                            MotoName = "ROUSER-NS125",
                            Price = 2600000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052965583_75665ecab6_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("3aeb31d0-f52e-4e77-a043-1e9f332d8939"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1126),
                            CategoryId = 3,
                            ChasisNum = 87654321,
                            Cylinder = 110,
                            Description = "La ROUSER-NS160TD cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 110cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "ROUSER",
                            Model = "NS160TD",
                            MotoName = "ROUSER-NS160TD",
                            Price = 3600000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052723066_b3a6736e08_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("a0f209f2-1d32-4eb9-8214-de8563cf04da"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1128),
                            CategoryId = 3,
                            ChasisNum = 87654321,
                            Cylinder = 200,
                            Description = "La ROUSER-NS200 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 200cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "ROUSER",
                            Model = "NS200",
                            MotoName = "ROUSER-NS200",
                            Price = 5400000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053169335_e52d3e9687_z.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("52a84943-29d7-49c6-b832-a1bf4e581505"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1131),
                            CategoryId = 3,
                            ChasisNum = 87654321,
                            Cylinder = 250,
                            Description = "La YAMAHA-FZ25ABS cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 250cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "FZ25ABS",
                            MotoName = "YAMAHA-FZ25ABS",
                            Price = 6800000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54051851202_4cf9d0daa1_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("a63fde75-e4ad-4465-b4f5-1258b17940db"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1133),
                            CategoryId = 3,
                            ChasisNum = 87654321,
                            Cylinder = 150,
                            Description = "YAMAHA-FZSFIV3 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 150cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "FZSFIV3",
                            MotoName = "YAMAHA-FZSFIV3",
                            Price = 5500000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052965548_283a4068e1_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("9b6509e7-4ebd-4afb-a90b-252ac605a3fb"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1135),
                            CategoryId = 3,
                            ChasisNum = 87654321,
                            Cylinder = 150,
                            Description = "La YAMAHA-FZX cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 150cc, 4 tiempos.",
                            Discount = 20,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "FZX",
                            MotoName = "YAMAHA-FZX",
                            Price = 5500000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052965558_26387c535b_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("a2dab439-3850-4a18-963d-f3e8e9f26258"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1138),
                            CategoryId = 3,
                            ChasisNum = 87654321,
                            Cylinder = 125,
                            Description = "La YAMAHA-YBR125 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 125cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "YBR125",
                            MotoName = "YAMAHA-YBR125",
                            Price = 2800000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052723056_b6d8b79cb6_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("4bf0b04c-0e7e-4ef2-bba0-3e1c19d3dc51"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1140),
                            CategoryId = 4,
                            ChasisNum = 87654321,
                            Cylinder = 450,
                            Description = "La HONDA-450R cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 450cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "450R",
                            MotoName = "HONDA-450R",
                            Price = 24000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053170115_0be57ee08d_c.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("5edf0e4a-a3bc-4024-aae6-4c28200cf28a"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1144),
                            CategoryId = 4,
                            ChasisNum = 87654321,
                            Cylinder = 250,
                            Description = "La HONDA-CRF250R cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 250cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "CRF250R",
                            MotoName = "HONDA-CRF250R",
                            Price = 19000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54051851832_ba8597d650_c.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("59a63083-1363-47d5-80ad-bdd555cfe891"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1147),
                            CategoryId = 4,
                            ChasisNum = 87654321,
                            Cylinder = 250,
                            Description = "La HONDA-CRF250RX cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 250cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "CRF250RX",
                            MotoName = "HONDA-CRF250RX",
                            Price = 22000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052723786_8e28337d58_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("f74ad2db-50a6-4741-b04f-99186ccc48b3"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1149),
                            CategoryId = 4,
                            ChasisNum = 87654321,
                            Cylinder = 450,
                            Description = "La HONDA-CRF450RX cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 450cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "CRF450RX",
                            MotoName = "HONDA-CRF450RX",
                            Price = 24000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053170100_ed677c45db_z.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("572c8c2b-c5e2-429c-8882-bade8f511e2a"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1151),
                            CategoryId = 4,
                            ChasisNum = 87654321,
                            Cylinder = 450,
                            Description = "La YAMAHA-NEWWR450F cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 450cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "NEWWR450F",
                            MotoName = "YAMAHA-NEWWR450F",
                            Price = 11400100m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052723811_cab777ec70_w.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("d918460e-c76f-46d2-95a9-19eb5ab52696"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1154),
                            CategoryId = 4,
                            ChasisNum = 87654321,
                            Cylinder = 125,
                            Description = "La YAMAHA-YZ125X cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 125cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "YZ125X",
                            MotoName = "YAMAHA-YZ125X",
                            Price = 7000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052966293_9b427b3c13_w.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("e942e059-2a2c-4e27-a04e-c4cf89d7b3f7"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1157),
                            CategoryId = 4,
                            ChasisNum = 87654321,
                            Cylinder = 250,
                            Description = "La YAMAHA-YZ250X cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 250cc, 4 tiempos.",
                            Discount = 10,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "YZ250X",
                            MotoName = "YAMAHA-YZ250X",
                            Price = 7400000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052966318_1324fe79e7_w.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("873d9514-0c41-4e40-ba54-127f1a0a9db7"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1159),
                            CategoryId = 4,
                            ChasisNum = 87654321,
                            Cylinder = 450,
                            Description = "La YAMAHA-YZ450FX cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 450cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "YZ450FX",
                            MotoName = "YAMAHA-YZ450FX",
                            Price = 10000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54051851792_51fc2a1f08_w.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("2e960f49-574f-49c2-ae82-2392322f00c9"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1162),
                            CategoryId = 5,
                            ChasisNum = 87654321,
                            Cylinder = 500,
                            Description = "La HONDA-CB500X cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 500cc, 4 tiempos.",
                            Discount = 5,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "CB500X",
                            MotoName = "HONDA-CB500X",
                            Price = 19000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052725166_7675f4cf13_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("4eb1e975-ca93-4789-9b8e-b3198b0a0ea7"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1166),
                            CategoryId = 5,
                            ChasisNum = 87654321,
                            Cylinder = 1100,
                            Description = "La HONDA-CRF1100 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 1100cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "CRF1100",
                            MotoName = "HONDA-CRF1100",
                            Price = 55200000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052725126_ef4c4f2276_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("63779011-db36-4f0d-a29b-d85a043281e3"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1168),
                            CategoryId = 5,
                            ChasisNum = 87654321,
                            Cylinder = 1100,
                            Description = "La HONDA-CRF1100ADVENTURE cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 1100cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "CRF1100ADVENTURE",
                            MotoName = "HONDA-CRF1100ADVENTURE",
                            Price = 55200000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54051853212_235e0bfe5d_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("2f67e34a-b3c3-4ab5-a365-bbb4bad67054"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1171),
                            CategoryId = 5,
                            ChasisNum = 87654321,
                            Cylinder = 750,
                            Description = "La HONDA-NC750X cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 750cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "NC750X",
                            MotoName = "HONDA-NC750X",
                            Price = 21600000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052967743_1cf44bbee9_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("a48ba5e4-eb5e-4839-8795-f199868f2f10"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1173),
                            CategoryId = 5,
                            ChasisNum = 87654321,
                            Cylinder = 300,
                            Description = "La KAWASAKI-VERSYS300 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 300cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "KAWASAKI",
                            Model = "VERSYS300",
                            MotoName = "KAWASAKI-VERSYS300",
                            Price = 15600000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052967693_3df6137024_c.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("808e40d2-70f4-4b1a-9cc8-c9ea2a285602"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1175),
                            CategoryId = 5,
                            ChasisNum = 87654321,
                            Cylinder = 650,
                            Description = "La KAWASAKI-VERSYS650 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 650cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "KAWASAKI",
                            Model = "VERSYS650",
                            MotoName = "KAWASAKI-VERSYS650",
                            Price = 26400000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052967683_dbe595e46d_c.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("ac36db5a-53f9-4ca0-8e79-3943cedec4ce"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1178),
                            CategoryId = 5,
                            ChasisNum = 87654321,
                            Cylinder = 700,
                            Description = "La YAMAHA-NEWTENERE700 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 700cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "NEWTENERE700",
                            MotoName = "YAMAHA-NEWTENERE700",
                            Price = 13500000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54051853202_a9d886ae64_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("e9ed2282-69c1-46d8-939f-295b339559c9"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1180),
                            CategoryId = 5,
                            ChasisNum = 87654321,
                            Cylinder = 1200,
                            Description = "La YAMAHA-XT1200 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 1200cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "XT1200",
                            MotoName = "YAMAHA-XT1200",
                            Price = 55000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053171435_6b3ecd17eb_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("1fd2aef3-9c02-46f5-8f66-e84c4b906f65"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1185),
                            CategoryId = 6,
                            ChasisNum = 87654321,
                            Cylinder = 125,
                            Description = "La HONDA-CB125FTWISTER cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 125cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "CB125FTWISTER",
                            MotoName = "HONDA-CB125FTWISTER",
                            Price = 3200000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54051852407_4ce9eaf366_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("8605a13a-0baa-4ab6-8d49-a05c6943994f"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1188),
                            CategoryId = 6,
                            ChasisNum = 87654321,
                            Cylinder = 300,
                            Description = "La HONDA-CB300FTWISTER cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 300cc, 4 tiempos.",
                            Discount = 10,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "CB300FTWISTER",
                            MotoName = "HONDA-CB300FTWISTER",
                            Price = 7890000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053170650_05f98b2d9a_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("75f421ce-c806-4e83-922d-c4e823d7aa7e"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1191),
                            CategoryId = 6,
                            ChasisNum = 87654321,
                            Cylinder = 500,
                            Description = "La HONDA-CB500F cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 500cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "CB500F",
                            MotoName = "HONDA-CB500F",
                            Price = 18000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052966883_7069860413_z.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("a2c791d9-44d1-40e6-95af-8da73df3770f"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1193),
                            CategoryId = 6,
                            ChasisNum = 87654321,
                            Cylinder = 750,
                            Description = "La HONDA-CB750HORNET cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 750cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "CB750HORNET",
                            MotoName = "HONDA-CB750HORNET",
                            Price = 19200000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052724331_545ff1889d_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("e7e47878-c1c6-4e72-a5cd-c9e6ebe95013"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1196),
                            CategoryId = 6,
                            ChasisNum = 87654321,
                            Cylinder = 650,
                            Description = "La YAMAHA-MT03 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 650cc, 4 tiempos.",
                            Discount = 15,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "MT03",
                            MotoName = "YAMAHA-MT03",
                            Price = 9600000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053049019_b3ba8377a3_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("9af5ddd9-9180-45dd-b6ee-d6b762fc80de"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1198),
                            CategoryId = 6,
                            ChasisNum = 87654321,
                            Cylinder = 700,
                            Description = "La YAMAHA-MT07 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 700cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "MT07",
                            MotoName = "YAMAHA-MT07",
                            Price = 12000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053170675_e11b6950ca_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("3cf08928-9c42-4671-846b-a87261a093b0"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1200),
                            CategoryId = 6,
                            ChasisNum = 87654321,
                            Cylinder = 850,
                            Description = "La YAMAHA-MT09 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 850cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "MT09",
                            MotoName = "YAMAHA-MT09",
                            Price = 16500000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053049049_df5a0149ed_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("255b079a-7221-4416-a8ec-b525e278d901"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1203),
                            CategoryId = 6,
                            ChasisNum = 87654321,
                            Cylinder = 1000,
                            Description = "La YAMAHA-MT10 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 1000cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "MT10",
                            MotoName = "YAMAHA-MT10",
                            Price = 27000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053049024_a643ceec91_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("a4914630-66fa-4dd0-84fd-24b741dcd52b"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1205),
                            CategoryId = 7,
                            ChasisNum = 87654321,
                            Cylinder = 500,
                            Description = "La BENELLI-502CRUISER cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 500cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "BENELLI",
                            Model = "502CRUISER",
                            MotoName = "BENELLI-502CRUISER",
                            Price = 13825000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54051852647_8492c767fb.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("0f578ae9-87f8-4e67-82dc-0ab6e31fa1ec"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1209),
                            CategoryId = 7,
                            ChasisNum = 87654321,
                            Cylinder = 400,
                            Description = "La BENELLI-IMPERIALE400 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 400cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "BENELLI",
                            Model = "IMPERIALE400",
                            MotoName = "BENELLI-IMPERIALE400",
                            Price = 7420000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54051852632_abbe287943.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("beea9436-dadd-47e7-9d19-567577f0d931"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1212),
                            CategoryId = 7,
                            ChasisNum = 87654321,
                            Cylinder = 250,
                            Description = "La BENELLI-LEONCINO250 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 250cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "BENELLI",
                            Model = "LEONCINO250",
                            MotoName = "BENELLI-LEONCINO250",
                            Price = 6450000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54051852642_87d6c905e7.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("e45e529d-53cd-4f3b-8fa0-f20ed56d875e"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1214),
                            CategoryId = 7,
                            ChasisNum = 87654321,
                            Cylinder = 150,
                            Description = "La ZANELLA-CCECATO60 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 150cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "ZANELLA",
                            Model = "CCECATO60",
                            MotoName = "ZANELLA-CCECATO60",
                            Price = 2890000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052967163_65d5be1736.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("181f6247-a775-46af-bc87-b3d2a3f79c6e"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1216),
                            CategoryId = 7,
                            ChasisNum = 87654321,
                            Cylinder = 150,
                            Description = "La ZANELLA-CCECATOR150 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 150cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "ZANELLA",
                            Model = "CCECATOR150",
                            MotoName = "ZANELLA-CCECATOR150 ",
                            Price = 2000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053170900_ac988f9146.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("8df1bbca-2641-49f0-ad66-60451a12c124"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1219),
                            CategoryId = 7,
                            ChasisNum = 87654321,
                            Cylinder = 250,
                            Description = "La ZANELLA-CECCATOX250 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 250cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "ZANELLA",
                            Model = "CECCATOX250",
                            MotoName = "ZANELLA-CECCATOX250",
                            Price = 4600000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052967153_21968c0114.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("67db922d-251d-4b83-be24-29af3ced9583"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1221),
                            CategoryId = 7,
                            ChasisNum = 87654321,
                            Cylinder = 150,
                            Description = "La ZANELLA-SAPUCAI150 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 150cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "ZANELLA",
                            Model = "SAPUCAI150",
                            MotoName = "ZANELLA-SAPUCAI150",
                            Price = 1849000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053049244_b9b7ebea2e.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("22c89d1e-f8da-472b-8254-f55f8831063b"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1224),
                            CategoryId = 8,
                            ChasisNum = 87654321,
                            Cylinder = 650,
                            Description = "La HONDA-CBR650R cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 650cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "CBR650R",
                            MotoName = "HONDA-CBR650R",
                            Price = 12820000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54051851657_5db0101ba3_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("28dffafe-6b57-4593-9822-cf6abe58e827"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1226),
                            CategoryId = 8,
                            ChasisNum = 87654321,
                            Cylinder = 1000,
                            Description = "La HONDA-CBR1000RR cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 1000cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "CBR1000RR",
                            MotoName = "HONDA-CBR1000RR",
                            Price = 48000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053169895_f58b5a1c8c_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("2b0f13d9-8201-466b-9005-9de6d932a714"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1230),
                            CategoryId = 8,
                            ChasisNum = 87654321,
                            Cylinder = 1000,
                            Description = "La HONDA-CBR1000SP cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 1000cc, 4 tiempos.",
                            Discount = 20,
                            EngineNum = 12345678,
                            Mark = "HONDA",
                            Model = "CBR1000SP",
                            MotoName = "HONDA-CBR1000SP",
                            Price = 48000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052966098_41a8786f3c_b.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("0d5aa725-4416-437c-a1e2-977aa6598200"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1233),
                            CategoryId = 8,
                            ChasisNum = 87654321,
                            Cylinder = 110,
                            Description = "La KAWASAKI-NINJA650 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 650cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "KAWASAKI",
                            Model = "NINJA650",
                            MotoName = "KAWASAKI-NINJA650",
                            Price = 21000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052966093_2668c66a23_z.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("02e07563-86f1-4d59-aa22-0e804e5359e5"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1235),
                            CategoryId = 8,
                            ChasisNum = 87654321,
                            Cylinder = 1000,
                            Description = "La YAMAHA-R1 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 1000cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "R1",
                            MotoName = "YAMAHA-R1",
                            Price = 24000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052723496_e9fd31c1ce_w.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("dfe165d7-abb7-47ed-a076-fcdbc6f41fdb"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1237),
                            CategoryId = 8,
                            ChasisNum = 87654321,
                            Cylinder = 350,
                            Description = "La YAMAHA-R3A cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 350cc, 4 tiempos.",
                            Discount = 10,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "R3A",
                            MotoName = "YAMAHA-R3A",
                            Price = 5820000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052966078_e4bd6a7781_w.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("7e3ad06b-515b-4751-95c0-38eb906fc078"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1240),
                            CategoryId = 8,
                            ChasisNum = 87654321,
                            Cylinder = 700,
                            Description = "La YAMAHA-R7 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 700cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "R7",
                            MotoName = "YAMAHA-R7",
                            Price = 9866000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54052723516_51ed4df75c_w.jpg"
                        },
                        new
                        {
                            MotoId = new Guid("c1547712-57cf-4c92-b137-e2099775d9a7"),
                            Age = new DateTime(2024, 10, 22, 13, 10, 34, 418, DateTimeKind.Local).AddTicks(1242),
                            CategoryId = 8,
                            ChasisNum = 87654321,
                            Cylinder = 155,
                            Description = "La YAMAHA-R15 cuenta con un diseño deportivo, ideal para la ciudad y los recorridos de media distancia. Motor de 155cc, 4 tiempos.",
                            Discount = 0,
                            EngineNum = 12345678,
                            Mark = "YAMAHA",
                            Model = "R15",
                            MotoName = "YAMAHA-R15",
                            Price = 4000000m,
                            StockCurrent = 10,
                            StockMax = 20,
                            StockMin = 5,
                            imageUrl = "https://live.staticflickr.com/65535/54053169865_11db74cf7e_w.jpg"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Taxes")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDiscount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalPay")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SaleId");

                    b.ToTable("Sale");
                });

            modelBuilder.Entity("Domain.Entities.SaleMoto", b =>
                {
                    b.Property<int>("ShoppingCartId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ShoppingCartId"));

                    b.Property<int?>("BuyOrderbuyId")
                        .HasColumnType("int");

                    b.Property<int>("Discount")
                        .HasColumnType("int");

                    b.Property<Guid>("Mot")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Sale")
                        .HasColumnType("int");

                    b.HasKey("ShoppingCartId");

                    b.HasIndex("BuyOrderbuyId");

                    b.HasIndex("Mot");

                    b.HasIndex("Sale");

                    b.ToTable("SaleMoto");
                });

            modelBuilder.Entity("Domain.Entities.Seller", b =>
                {
                    b.Property<Guid>("SellerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SellerId");

                    b.ToTable("Sellers");
                });

            modelBuilder.Entity("Domain.Entities.Techn", b =>
                {
                    b.Property<Guid>("TecnicoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Dni")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Locality")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Phone")
                        .HasColumnType("int");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TecnicoId");

                    b.ToTable("Techns");
                });

            modelBuilder.Entity("Domain.Entities.Turn", b =>
                {
                    b.Property<int>("TurnId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TurnId"));

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Motoid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SaleId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TechnId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TypeService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TurnId");

                    b.HasIndex("ClientId");

                    b.HasIndex("Motoid");

                    b.HasIndex("SaleId");

                    b.HasIndex("TechnId");

                    b.ToTable("Turns");
                });

            modelBuilder.Entity("Domain.Entities.Moto", b =>
                {
                    b.HasOne("Domain.Entities.Category", "Category")
                        .WithMany("Motos")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Domain.Entities.SaleMoto", b =>
                {
                    b.HasOne("Domain.Entities.Buy", null)
                        .WithMany("SaleMotos")
                        .HasForeignKey("BuyOrderbuyId");

                    b.HasOne("Domain.Entities.Moto", "Moto")
                        .WithMany("SaleMotos")
                        .HasForeignKey("Mot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sale", "Venta")
                        .WithMany("SaleMotos")
                        .HasForeignKey("Sale")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moto");

                    b.Navigation("Venta");
                });

            modelBuilder.Entity("Domain.Entities.Turn", b =>
                {
                    b.HasOne("Domain.Entities.Client", "client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Moto", "Moto")
                        .WithMany()
                        .HasForeignKey("Motoid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Sale", "sale")
                        .WithMany()
                        .HasForeignKey("SaleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Entities.Techn", "techn")
                        .WithMany("Turns")
                        .HasForeignKey("TechnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Moto");

                    b.Navigation("client");

                    b.Navigation("sale");

                    b.Navigation("techn");
                });

            modelBuilder.Entity("Domain.Entities.Buy", b =>
                {
                    b.Navigation("SaleMotos");
                });

            modelBuilder.Entity("Domain.Entities.Category", b =>
                {
                    b.Navigation("Motos");
                });

            modelBuilder.Entity("Domain.Entities.Moto", b =>
                {
                    b.Navigation("SaleMotos");
                });

            modelBuilder.Entity("Domain.Entities.Sale", b =>
                {
                    b.Navigation("SaleMotos");
                });

            modelBuilder.Entity("Domain.Entities.Techn", b =>
                {
                    b.Navigation("Turns");
                });
#pragma warning restore 612, 618
        }
    }
}
